workflows:
  react-native-ios:
    name: React Native iOS App
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Apple Connect App Mgr
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.huntergames.pumpkinpatch
      vars:
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_ID: $APP_STORE_CONNECT_KEY_ID
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        APP_ID: 6749664824
      node: 20
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm ci
          npm install -g @capacitor/cli @capacitor/core @capacitor/ios
      - name: Build web application
        script: |
          npm run build
      - name: Initialize and sync Capacitor
        script: |
          npx cap sync ios
          # Ensure App Tracking Transparency framework is available
          echo "Verifying iOS deployment target for ATT framework..."
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App && pod install
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Set build number to 36
        script: |
          cd ios/App
          agvtool new-version -all 36
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace ios/App/App.xcworkspace \
            --scheme App \
            --config Release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false

  pwa-build:
    name: PWA Build and Deploy
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      node: 20
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build PWA
        script: |
          npm run build
      - name: Generate build artifacts
        script: |
          echo "PWA built successfully. Ready for deployment."
    artifacts:
      - client/dist/**
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false